# run with command
# WHOAMI="$(whoami)" docker-compose up
# or simply
# WHOAMI=<output of echo $USER> docker-compose up

version: "3"
services:

  db:
    image: cml87/wikijs_db:nano #postgres:11-alpine
    container_name: wikijs_db
    hostname: wikijs_db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijs21set
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - wikijs-db_vol:/var/lib/postgresql/data

  wiki:
    image: cml87/wikijs_app:nano  #requarks/wiki:2
    container_name: wikijs_app
    hostname: wikijs_app
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs21set
      DB_NAME: wiki
    restart: unless-stopped
    volumes:
      - '/home/${WHOAMI}/.ssh/wikijs_app-sshkey:${CONTAINER_PRIVATE_WIKIJS_SSH_KEY_PATH}'
    ports:
      - "70:3000"

volumes:
  wikijs-db_vol:
    external: true
