version: "3"
services:

  db:
    image: postgres:11-alpine
    container_name: wikijs_db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijs21set
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - wikijs-db_vol:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    container_name: wikijs_app
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs21set
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "70:3000"

volumes:
  wikijs-db_vol:
    external: true
